const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const spring = html.match(/<details\b[^>]*id="springSection"[^>]*>([\s\S]*?)<\/details>/);
assert.ok(spring, 'Spring trimester must use a native collapsible details element');
assert.match(spring[1], /<summary class="section-title">Spring 2026/);
assert.match(spring[1], /Final Grade:.*A-/);
assert.match(spring[1], /id="trendChartContainer"/, 'Spring chart must collapse with its trimester');
assert.match(spring[1], /id="springGrid"/, 'Spring tests must collapse with their trimester');
assert.equal((html.match(/id="trendChartContainer"/g) || []).length, 1);
assert.ok(!spring[1].includes('id="precalculusSection"'), 'Pre-Calculus must remain independent');
assert.match(html, /\.section-title::after\s*\{[^}]*border-right:[^}]*border-bottom:/);
assert.match(html, /details\[open\] > \.section-title::after\s*\{[^}]*rotate\(45deg\)/);
const sections = [...html.matchAll(/<details class="dash-section" id="([^"]+)"([^>]*)>/g)];
assert.deepEqual(sections.map(match => match[1]), ['precalculusSection', 'springSection', 'winterSection']);
assert.match(sections[0][2], /\bopen\b/, 'Current Pre-Calculus trimester starts open');
sections.slice(1).forEach(match => assert.ok(!/\bopen\b/.test(match[2]), 'Archived trimesters start collapsed'));
assert.match(html, /Fall 2026 &middot; Pre-Calculus/);
assert.match(html, /Spring 2026 &middot; Algebra II/);
assert.match(html, /Winter 2025-26 &middot; Algebra II/);
const header = html.match(/<header class="app-hd">([\s\S]*?)<\/header>/)[1];
assert.match(header, /<h1>Motor City Math<\/h1>/);
assert.ok(!header.includes('Algebra II'), "Page header must not be tied to last year's course");
const precalculus = html.match(/<details\b[^>]*id="precalculusSection"[^>]*>([\s\S]*?)<\/details>/)[1];
assert.match(precalculus, /<a class="test-link" href="tests\/assessment-1-functions-75min.pdf"/);
assert.equal((html.match(/class="hero hero-link"/g) || []).length, 0, 'Completed prep test no longer has an ungraded hero');
assert.ok(!html.includes('Spring Logs &middot;'), 'Archived Spring assignment must not be featured');
assert.match(precalculus, /Functions &amp; Polynomial Review/);
assert.match(spring[1], /Polynomials, Rational Functions &amp; Logarithms/);
assert.match(html, /Exponents, Function Transformations &amp; Quadratics/);
assert.ok(fs.existsSync(path.join(__dirname, 'assessment-1-functions-75min.pdf')));
console.log('dashboard-trimester-collapse: PASS');
