// aria-describedby error association test -- WCAG 1.3.1
// Input validation errors must use aria-describedby to associate error element with input field
// This allows screen readers to announce the error when the input receives focus

const fs = require('fs');
const path = require('path');

let pass = 0, fail = 0;
function test(name, result) {
    if (result) { console.log('  \u2705 ' + name); pass++; }
    else        { console.log('  \u274c ' + name); fail++; }
}

console.log('\u{1F3C0} aria-describedby-errors.test.js\n');

var examSrc = fs.readFileSync(path.join(__dirname, '../../exam.html'), 'utf-8');

console.log('\u2500\u2500 aria-describedby error association (WCAG 1.3.1) \u2500\u2500\n');

// 1. aria-describedby attribute appears on input elements (generated by renderInput or checkAnswer)
var hasDescribedby = examSrc.includes('aria-describedby');
test('aria-describedby used in exam.html', hasDescribedby);

// 2. Error elements have matching IDs (error-{questionId} or similar)
var hasErrorId = examSrc.includes('error-') || examSrc.includes('-error') ||
                 examSrc.includes('errorId') || examSrc.includes('err-');
test('Error elements have identifiable IDs for aria-describedby linking', hasErrorId);

// 3. checkAnswer or renderInput sets aria-describedby dynamically on error state
var checkAnswerIdx = examSrc.indexOf('function checkAnswer');
var renderInputIdx = examSrc.indexOf('function renderInput');
var hasDescribedbyInFns = false;
if (checkAnswerIdx !== -1) {
    hasDescribedbyInFns = examSrc.substring(checkAnswerIdx, checkAnswerIdx + 5000).includes('aria-describedby');
}
if (!hasDescribedbyInFns && renderInputIdx !== -1) {
    hasDescribedbyInFns = examSrc.substring(renderInputIdx, renderInputIdx + 3000).includes('aria-describedby');
}
test('checkAnswer or renderInput sets aria-describedby on error', hasDescribedbyInFns || hasDescribedby);

// 4. aria-invalid set on input when answer is wrong
var hasAriaInvalid = examSrc.includes('aria-invalid');
test('aria-invalid set on input when answer is wrong', hasAriaInvalid);

// 5. Error message container role=alert or aria-live=assertive for immediate announcement
var hasAlertOrAssertive = examSrc.includes('role="alert"') || examSrc.includes("role='alert'") ||
                          examSrc.includes('aria-live="assertive"') || examSrc.includes("aria-live='assertive'");
test('Error container has role=alert or aria-live=assertive', hasAlertOrAssertive);

console.log('\n' + '='.repeat(50));
console.log('aria-describedby-errors: ' + (pass+fail) + ' checks, ' + pass + ' pass, ' + fail + ' fail');
if (fail === 0) { console.log('PASS'); process.exit(0); }
else            { console.log('FAIL'); process.exit(1); }
